"""lead lifecycle redesign

Revision ID: 30a3b8e89616
Revises: d6fbf129e273
Create Date: 2026-08-05 14:11:59.349771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30a3b8e89616'
down_revision: Union[str, Sequence[str], None] = 'd6fbf129e273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


lead_priority_enum = sa.Enum('hot', 'warm', 'cold', name='lead_priority')
conversion_source_enum = sa.Enum(
    'agreement_signed', 'service_purchased', 'registration_completed', 'payment_received', 'other',
    name='conversion_source',
)
lost_reason_enum = sa.Enum(
    'no_response_after_7_attempts', 'not_interested', 'budget_issue', 'chose_another_consultancy',
    'wrong_number', 'invalid_lead', 'not_eligible', 'duplicate_lead', 'other',
    name='lost_reason',
)


def upgrade() -> None:
    """Upgrade schema."""
    # `op.add_column` (unlike `op.create_table`) does not auto-create a new Postgres
    # enum type for an inline `sa.Enum` — create these three explicitly first.
    bind = op.get_bind()
    lead_priority_enum.create(bind, checkfirst=True)
    conversion_source_enum.create(bind, checkfirst=True)
    lost_reason_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_follow_ups',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('counsellor_id', sa.UUID(), nullable=True),
    sa.Column('method', sa.Enum('phone_call', 'whatsapp', 'email', 'sms', 'in_person', 'video_meeting', name='follow_up_method'), nullable=False),
    sa.Column('outcome', sa.Enum('no_answer', 'busy', 'call_back_later', 'interested', 'very_interested', 'documents_pending', 'thinking', 'wrong_number', 'not_eligible', 'duplicate', 'converted_to_prospect', 'converted_to_client', name='follow_up_outcome'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_follow_up_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number >= 1 AND attempt_number <= 7', name=op.f('ck_lead_follow_ups_lead_follow_ups_attempt_number_range')),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], name=op.f('fk_lead_follow_ups_counsellor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_follow_ups_lead_id_leads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_follow_ups'))
    )
    op.create_index('idx_lead_follow_ups_counsellor_id', 'lead_follow_ups', ['counsellor_id'], unique=False)
    op.create_index('idx_lead_follow_ups_lead_id', 'lead_follow_ups', ['lead_id'], unique=False)
    op.create_index('idx_lead_follow_ups_scheduled_at', 'lead_follow_ups', ['scheduled_at'], unique=False)
    op.add_column('leads', sa.Column('priority', sa.Enum('hot', 'warm', 'cold', name='lead_priority', create_type=False), server_default='warm', nullable=False))
    op.add_column('leads', sa.Column('tags', sa.ARRAY(sa.String(length=50)), nullable=True))
    op.add_column('leads', sa.Column('qualified_by', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('qualified_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('converted_by', sa.UUID(), nullable=True))
    op.add_column('leads', sa.Column('converted_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('conversion_source', sa.Enum('agreement_signed', 'service_purchased', 'registration_completed', 'payment_received', 'other', name='conversion_source', create_type=False), nullable=True))
    op.add_column('leads', sa.Column('lost_reason', sa.Enum('no_response_after_7_attempts', 'not_interested', 'budget_issue', 'chose_another_consultancy', 'wrong_number', 'invalid_lead', 'not_eligible', 'duplicate_lead', 'other', name='lost_reason', create_type=False), nullable=True))
    op.add_column('leads', sa.Column('lost_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index('idx_leads_priority', 'leads', ['priority'], unique=False)
    op.create_foreign_key(op.f('fk_leads_converted_by_users'), 'leads', 'users', ['converted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_leads_qualified_by_users'), 'leads', 'users', ['qualified_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_leads_qualified_by_users'), 'leads', type_='foreignkey')
    op.drop_constraint(op.f('fk_leads_converted_by_users'), 'leads', type_='foreignkey')
    op.drop_index('idx_leads_priority', table_name='leads')
    op.drop_column('leads', 'lost_at')
    op.drop_column('leads', 'lost_reason')
    op.drop_column('leads', 'conversion_source')
    op.drop_column('leads', 'converted_at')
    op.drop_column('leads', 'converted_by')
    op.drop_column('leads', 'qualified_at')
    op.drop_column('leads', 'qualified_by')
    op.drop_column('leads', 'tags')
    op.drop_column('leads', 'priority')
    op.drop_index('idx_lead_follow_ups_scheduled_at', table_name='lead_follow_ups')
    op.drop_index('idx_lead_follow_ups_lead_id', table_name='lead_follow_ups')
    op.drop_index('idx_lead_follow_ups_counsellor_id', table_name='lead_follow_ups')
    op.drop_table('lead_follow_ups')
    # ### end Alembic commands ###

    bind = op.get_bind()
    lost_reason_enum.drop(bind, checkfirst=True)
    conversion_source_enum.drop(bind, checkfirst=True)
    lead_priority_enum.drop(bind, checkfirst=True)
