"""people foundation departments and employment events

Revision ID: 30f33c7754d2
Revises: 51353a3343d2
Create Date: 2026-08-10 17:25:31.649135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30f33c7754d2'
down_revision: Union[str, Sequence[str], None] = '51353a3343d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_departments_manager_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_departments_organization_id_name')
    )
    op.create_index('idx_departments_manager_id', 'departments', ['manager_id'], unique=False)
    op.create_index('idx_departments_organization_id', 'departments', ['organization_id'], unique=False)
    op.create_table('employee_employment_events',
    sa.Column('employee_profile_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('joined', 'promoted', 'department_changed', 'manager_changed', 'designation_changed', 'status_changed', 'probation_completed', 'contract_renewed', 'other', name='employment_event_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_employee_employment_events_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_profile_id'], ['employee_profiles.id'], name=op.f('fk_employee_employment_events_employee_profile_id_employee_profiles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_employee_employment_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_employment_events'))
    )
    op.create_index('idx_employee_employment_events_created_at', 'employee_employment_events', ['created_at'], unique=False)
    op.create_index('idx_employee_employment_events_employee_profile_id', 'employee_employment_events', ['employee_profile_id'], unique=False)
    op.create_index('idx_employee_employment_events_organization_id', 'employee_employment_events', ['organization_id'], unique=False)
    op.add_column('employee_profiles', sa.Column('department_id', sa.UUID(), nullable=True))
    # Unlike employment_event_type above (created implicitly by create_table),
    # this enum is only ever used in a standalone ADD COLUMN, which does not
    # auto-issue CREATE TYPE — it must be created explicitly first.
    employment_type_enum = sa.Enum('full_time', 'part_time', 'contract', 'intern', 'freelance', name='employment_type')
    employment_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('employee_profiles', sa.Column('employment_type', employment_type_enum, nullable=True))
    op.add_column('employee_profiles', sa.Column('probation_end_date', sa.Date(), nullable=True))
    op.add_column('employee_profiles', sa.Column('contract_start_date', sa.Date(), nullable=True))
    op.add_column('employee_profiles', sa.Column('contract_end_date', sa.Date(), nullable=True))
    op.create_index('idx_employee_profiles_department_id', 'employee_profiles', ['department_id'], unique=False)
    op.create_foreign_key(op.f('fk_employee_profiles_department_id_departments'), 'employee_profiles', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employee_profiles_department_id_departments'), 'employee_profiles', type_='foreignkey')
    op.drop_index('idx_employee_profiles_department_id', table_name='employee_profiles')
    op.drop_column('employee_profiles', 'contract_end_date')
    op.drop_column('employee_profiles', 'contract_start_date')
    op.drop_column('employee_profiles', 'probation_end_date')
    op.drop_column('employee_profiles', 'employment_type')
    sa.Enum(name='employment_type').drop(op.get_bind(), checkfirst=True)
    op.drop_column('employee_profiles', 'department_id')
    op.drop_index('idx_employee_employment_events_organization_id', table_name='employee_employment_events')
    op.drop_index('idx_employee_employment_events_employee_profile_id', table_name='employee_employment_events')
    op.drop_index('idx_employee_employment_events_created_at', table_name='employee_employment_events')
    op.drop_table('employee_employment_events')
    # create_table auto-creates enum types but drop_table does not auto-drop them.
    sa.Enum(name='employment_event_type').drop(op.get_bind(), checkfirst=True)
    op.drop_index('idx_departments_organization_id', table_name='departments')
    op.drop_index('idx_departments_manager_id', table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
