"""expand student profile with family details, education history, work experience

Revision ID: 31d14ea42645
Revises: 8f2a1c9d4e77
Create Date: 2026-08-05 17:18:21.739259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '31d14ea42645'
down_revision: Union[str, Sequence[str], None] = '8f2a1c9d4e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_education_history',
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('degree_level', postgresql.ENUM('certificate', 'diploma', 'advanced_diploma', 'bachelor', 'postgraduate_diploma', 'master', 'doctorate', name='degree_level', create_type=False), nullable=True),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_education_history_student_profile_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_education_history'))
    )
    op.create_index('idx_student_education_history_student_profile_id', 'student_education_history', ['student_profile_id'], unique=False)
    op.create_table('student_work_experience',
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_work_experience_student_profile_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_work_experience'))
    )
    op.create_index('idx_student_work_experience_student_profile_id', 'student_work_experience', ['student_profile_id'], unique=False)
    op.add_column('student_profiles', sa.Column('father_name', sa.String(length=150), nullable=True))
    op.add_column('student_profiles', sa.Column('mother_name', sa.String(length=150), nullable=True))
    op.add_column('student_profiles', sa.Column('birth_place', sa.String(length=150), nullable=True))
    op.add_column('student_profiles', sa.Column('permanent_address', sa.Text(), nullable=True))
    op.add_column('student_profiles', sa.Column('emergency_contact_name', sa.String(length=150), nullable=True))
    op.add_column('student_profiles', sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_profiles', 'emergency_contact_phone')
    op.drop_column('student_profiles', 'emergency_contact_name')
    op.drop_column('student_profiles', 'permanent_address')
    op.drop_column('student_profiles', 'birth_place')
    op.drop_column('student_profiles', 'mother_name')
    op.drop_column('student_profiles', 'father_name')
    op.drop_index('idx_student_work_experience_student_profile_id', table_name='student_work_experience')
    op.drop_table('student_work_experience')
    op.drop_index('idx_student_education_history_student_profile_id', table_name='student_education_history')
    op.drop_table('student_education_history')
    # ### end Alembic commands ###
