"""phase 2a subscription and seat management

Revision ID: 89cc92f54177
Revises: e009a611841b
Create Date: 2026-08-05 19:57:21.068071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89cc92f54177'
down_revision: Union[str, Sequence[str], None] = 'e009a611841b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

DEFAULT_ORGANIZATION_ID = "00000000-0000-0000-0000-000000000001"


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('starter', 'professional', 'enterprise', name='org_subscription_plan'), nullable=False),
    sa.Column('status', sa.Enum('trialing', 'active', 'past_due', 'cancelled', name='org_subscription_status'), server_default='trialing', nullable=False),
    sa.Column('billing_cycle', sa.Enum('monthly', 'yearly', name='billing_cycle'), server_default='monthly', nullable=False),
    sa.Column('included_staff_seats', sa.Integer(), nullable=True),
    sa.Column('extra_staff_seats', sa.Integer(), server_default='0', nullable=False),
    sa.Column('student_limit', sa.Integer(), nullable=True),
    sa.Column('storage_limit_mb', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('renewal_date', sa.Date(), nullable=True),
    sa.Column('trial_end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_subscriptions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_subscriptions')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_organization_subscriptions_organization_id'))
    )
    op.create_index('idx_organization_subscriptions_organization_id', 'organization_subscriptions', ['organization_id'], unique=False)
    op.create_index('idx_organization_subscriptions_status', 'organization_subscriptions', ['status'], unique=False)
    # ### end Alembic commands ###

    # The Default Organization already holds every pre-Phase-1 user (5+ real
    # accounts) — seed it with an unlimited (Enterprise-equivalent) subscription
    # so this migration never locks out existing data.
    op.execute(
        f"""
        INSERT INTO organization_subscriptions
            (id, organization_id, plan, status, billing_cycle,
             included_staff_seats, extra_staff_seats, student_limit, storage_limit_mb,
             price, created_at, updated_at)
        VALUES
            (gen_random_uuid(), '{DEFAULT_ORGANIZATION_ID}', 'enterprise', 'active', 'monthly',
             NULL, 0, NULL, NULL,
             0, now(), now())
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_organization_subscriptions_status', table_name='organization_subscriptions')
    op.drop_index('idx_organization_subscriptions_organization_id', table_name='organization_subscriptions')
    op.drop_table('organization_subscriptions')
    # ### end Alembic commands ###
