"""initial

Revision ID: 903d2bde03d8
Revises: 
Create Date: 2026-08-01 18:21:59.783510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '903d2bde03d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso2', sa.String(length=2), nullable=False),
    sa.Column('iso3', sa.String(length=3), nullable=True),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('flag_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries')),
    sa.UniqueConstraint('iso2', name=op.f('uq_countries_iso2')),
    sa.UniqueConstraint('iso3', name=op.f('uq_countries_iso3')),
    sa.UniqueConstraint('name', name=op.f('uq_countries_name'))
    )
    op.create_index('idx_countries_name', 'countries', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('student', 'counsellor', 'frontdesk', 'staff', 'admin', 'super_admin', name='user_role'), server_default='student', nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='user_status'), server_default='active', nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('email_verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('phone_verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('failed_login_attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('google_id', name=op.f('uq_users_google_id'))
    )
    op.create_index('idx_users_deleted_at', 'users', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_users_last_login_at', 'users', ['last_login_at'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('activity_type', sa.Enum('create', 'update', 'delete', 'login', 'logout', 'upload', 'download', 'assign', 'status_change', 'payment', 'other', name='activity_type'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index('idx_activity_logs_activity_type', 'activity_logs', ['activity_type'], unique=False)
    op.create_index('idx_activity_logs_created_at', 'activity_logs', ['created_at'], unique=False)
    op.create_index('idx_activity_logs_entity_type', 'activity_logs', ['entity_type'], unique=False)
    op.create_index('idx_activity_logs_user_id', 'activity_logs', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('passport', 'citizenship', 'national_id', 'academic_transcript', 'academic_certificate', 'provisional_certificate', 'character_certificate', 'english_test', 'cv', 'statement_of_purpose', 'recommendation_letter', 'offer_letter', 'visa', 'financial_document', 'medical_report', 'photo', 'other', name='document_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'uploaded', 'under_review', 'approved', 'rejected', 'expired', name='document_status'), server_default='pending', nullable=False),
    sa.Column('expiry_date', sa.String(length=10), nullable=True),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size IS NULL OR file_size >= 0', name=op.f('ck_documents_documents_file_size_non_negative')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_documents_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_documents_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index('idx_documents_document_type', 'documents', ['document_type'], unique=False)
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index('idx_documents_student_id', 'documents', ['student_id'], unique=False)
    op.create_index('idx_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_index('idx_documents_verified_by', 'documents', ['verified_by'], unique=False)
    op.create_table('employee_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('employee_code', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('designation', sa.String(length=100), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.String(length=30), server_default='active', nullable=True),
    sa.Column('office_location', sa.String(length=255), nullable=True),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name=op.f('fk_employee_profiles_manager_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_employee_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_profiles')),
    sa.UniqueConstraint('employee_code', name=op.f('uq_employee_profiles_employee_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_employee_profiles_user_id'))
    )
    op.create_index('idx_employee_profiles_manager_id', 'employee_profiles', ['manager_id'], unique=False)
    op.create_index('idx_employee_profiles_user_id', 'employee_profiles', ['user_id'], unique=False)
    op.create_table('leads',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('source', sa.Enum('website', 'walk_in', 'facebook', 'instagram', 'google', 'tiktok', 'linkedin', 'whatsapp', 'phone', 'referral', 'event', 'other', name='lead_source'), server_default='website', nullable=False),
    sa.Column('status', sa.Enum('new', 'contacted', 'follow_up', 'qualified', 'converted', 'lost', name='lead_status'), server_default='new', nullable=False),
    sa.Column('interested_country', sa.String(length=100), nullable=True),
    sa.Column('interested_course', sa.String(length=255), nullable=True),
    sa.Column('preferred_intake', sa.String(length=50), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('converted_user_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('next_follow_up_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(phone)) > 0', name=op.f('ck_leads_leads_phone_not_empty')),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_leads_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['converted_user_id'], ['users.id'], name=op.f('fk_leads_converted_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leads'))
    )
    op.create_index('idx_leads_assigned_to', 'leads', ['assigned_to'], unique=False)
    op.create_index('idx_leads_converted_user_id', 'leads', ['converted_user_id'], unique=False)
    op.create_index('idx_leads_email_unique_not_null', 'leads', ['email'], unique=True, postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('idx_leads_next_follow_up_at', 'leads', ['next_follow_up_at'], unique=False)
    op.create_index('idx_leads_phone', 'leads', ['phone'], unique=False)
    op.create_index('idx_leads_source', 'leads', ['source'], unique=False)
    op.create_index('idx_leads_status', 'leads', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('system', 'application', 'payment', 'appointment', 'task', 'document', name='notification_type'), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'sms', 'whatsapp', name='notification_channel'), server_default='in_app', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False, postgresql_where=sa.text('is_read = FALSE'))
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('education_level', sa.Enum('bachelor', 'diploma', '10+2', 'masters', name='institution_type'), nullable=False),
    sa.Column('university_name', sa.String(length=255), nullable=True),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=True),
    sa.Column('gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('preferred_country', sa.String(length=100), nullable=True),
    sa.Column('preferred_program', sa.String(length=255), nullable=True),
    sa.Column('preferred_intake', sa.String(length=50), nullable=True),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_student_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_student_profiles_user_id'))
    )
    op.create_index('idx_student_profiles_deleted_at', 'student_profiles', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_student_profiles_user_id', 'student_profiles', ['user_id'], unique=False)
    op.create_table('universities',
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('is_partner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_universities_country_id_countries'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universities'))
    )
    op.create_index('idx_universities_country_id', 'universities', ['country_id'], unique=False)
    op.create_index('idx_universities_is_active', 'universities', ['is_active'], unique=False)
    op.create_index('idx_universities_name', 'universities', ['name'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index('idx_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('idx_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('counsellor_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('appointment_type', sa.Enum('consultation', 'document_review', 'application_review', 'visa_consultation', 'follow_up', 'phone_call', 'video_call', 'office_visit', 'other', name='appointment_type'), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'confirmed', 'completed', 'cancelled', 'no_show', 'rescheduled', name='appointment_status'), server_default='scheduled', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], name=op.f('fk_appointments_counsellor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_appointments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_appointments_lead_id_leads'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_appointments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_appointments'))
    )
    op.create_index('idx_appointments_counsellor_id', 'appointments', ['counsellor_id'], unique=False)
    op.create_index('idx_appointments_lead_id', 'appointments', ['lead_id'], unique=False)
    op.create_index('idx_appointments_start_time', 'appointments', ['start_time'], unique=False)
    op.create_index('idx_appointments_status', 'appointments', ['status'], unique=False)
    op.create_index('idx_appointments_student_id', 'appointments', ['student_id'], unique=False)
    op.create_table('lead_activities',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('lead_created', 'call', 'email', 'whatsapp', 'sms', 'meeting', 'note', 'status_changed', 'assigned', 'follow_up', 'document_received', 'converted', 'lost', name='lead_activity_type'), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('old_status', sa.Enum('new', 'contacted', 'follow_up', 'qualified', 'converted', 'lost', name='lead_status'), nullable=True),
    sa.Column('new_status', sa.Enum('new', 'contacted', 'follow_up', 'qualified', 'converted', 'lost', name='lead_status'), nullable=True),
    sa.Column('due_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_lead_activities_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_lead_activities_performed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lead_activities'))
    )
    op.create_index('idx_lead_activities_created_at', 'lead_activities', ['created_at'], unique=False)
    op.create_index('idx_lead_activities_lead_id', 'lead_activities', ['lead_id'], unique=False)
    op.create_index('idx_lead_activities_performed_by', 'lead_activities', ['performed_by'], unique=False)
    op.create_table('programs',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('degree_level', sa.Enum('certificate', 'diploma', 'advanced_diploma', 'bachelor', 'postgraduate_diploma', 'master', 'doctorate', name='degree_level'), nullable=True),
    sa.Column('field_of_study', sa.String(length=100), nullable=True),
    sa.Column('duration_months', sa.SmallInteger(), nullable=True),
    sa.Column('tuition_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('intake', sa.String(length=50), nullable=True),
    sa.Column('minimum_gpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('minimum_ielts', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], name=op.f('fk_programs_university_id_universities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_programs'))
    )
    op.create_index('idx_programs_is_active', 'programs', ['is_active'], unique=False)
    op.create_index('idx_programs_name', 'programs', ['name'], unique=False)
    op.create_index('idx_programs_university_id', 'programs', ['university_id'], unique=False)
    op.create_table('student_english_tests',
    sa.Column('student_profile_id', sa.UUID(), nullable=False),
    sa.Column('test_type', sa.Enum('ielts', 'pte', 'toefl', 'duolingo', 'other', name='english_test_type'), nullable=False),
    sa.Column('test_date', sa.String(length=10), nullable=True),
    sa.Column('overall_score', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], name=op.f('fk_student_english_tests_student_profile_id_student_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_english_tests')),
    sa.UniqueConstraint('student_profile_id', 'test_type', 'test_date', name='uq_student_english_tests_student_profile_id_test_type_test_date')
    )
    op.create_index('idx_student_english_tests_student_profile_id', 'student_english_tests', ['student_profile_id'], unique=False)
    op.create_index('idx_student_english_tests_test_type', 'student_english_tests', ['test_type'], unique=False)
    op.create_table('intakes',
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_intakes_program_id_programs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intakes'))
    )
    op.create_index('idx_intakes_is_active', 'intakes', ['is_active'], unique=False)
    op.create_index('idx_intakes_program_id', 'intakes', ['program_id'], unique=False)
    op.create_table('applications',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('counsellor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'documents_pending', 'ready_to_submit', 'submitted', 'under_review', 'offer_received', 'offer_accepted', 'offer_declined', 'visa_processing', 'visa_approved', 'visa_rejected', 'enrolled', 'withdrawn', 'rejected', name='application_status'), server_default='draft', nullable=False),
    sa.Column('application_date', sa.String(length=10), nullable=True),
    sa.Column('submission_date', sa.String(length=10), nullable=True),
    sa.Column('offer_received_date', sa.String(length=10), nullable=True),
    sa.Column('visa_applied_date', sa.String(length=10), nullable=True),
    sa.Column('visa_decision_date', sa.String(length=10), nullable=True),
    sa.Column('enrollment_date', sa.String(length=10), nullable=True),
    sa.Column('tuition_fee', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('scholarship_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('university_application_id', sa.String(length=100), nullable=True),
    sa.Column('intake_id', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_id'], ['users.id'], name=op.f('fk_applications_counsellor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name=op.f('fk_applications_intake_id_intakes')),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], name=op.f('fk_applications_program_id_programs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_applications_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('idx_applications_counsellor_id', 'applications', ['counsellor_id'], unique=False)
    op.create_index('idx_applications_intake_id', 'applications', ['intake_id'], unique=False)
    op.create_index('idx_applications_program_id', 'applications', ['program_id'], unique=False)
    op.create_index('idx_applications_status', 'applications', ['status'], unique=False)
    op.create_index('idx_applications_student_id', 'applications', ['student_id'], unique=False)
    op.create_table('application_documents',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_documents_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_application_documents_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_documents')),
    sa.UniqueConstraint('application_id', 'document_id', name='uq_application_documents_application_id_document_id')
    )
    op.create_index('idx_application_documents_application_id', 'application_documents', ['application_id'], unique=False)
    op.create_index('idx_application_documents_document_id', 'application_documents', ['document_id'], unique=False)
    op.create_table('application_status_history',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('draft', 'documents_pending', 'ready_to_submit', 'submitted', 'under_review', 'offer_received', 'offer_accepted', 'offer_declined', 'visa_processing', 'visa_approved', 'visa_rejected', 'enrolled', 'withdrawn', 'rejected', name='application_status'), nullable=True),
    sa.Column('new_status', sa.Enum('draft', 'documents_pending', 'ready_to_submit', 'submitted', 'under_review', 'offer_received', 'offer_accepted', 'offer_declined', 'visa_processing', 'visa_approved', 'visa_rejected', 'enrolled', 'withdrawn', 'rejected', name='application_status'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_status_history_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_application_status_history_changed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_status_history'))
    )
    op.create_index('idx_application_status_history_application_id', 'application_status_history', ['application_id'], unique=False)
    op.create_index('idx_application_status_history_changed_by', 'application_status_history', ['changed_by'], unique=False)
    op.create_table('payments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('payment_method', sa.Enum('cash', 'bank_transfer', 'esewa', 'khalti', 'fonepay', 'credit_card', 'debit_card', 'other', name='payment_method'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', 'refunded', 'cancelled', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('transaction_reference', sa.String(length=255), nullable=True),
    sa.Column('payment_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_payments_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_payments_student_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('idx_payments_application_id', 'payments', ['application_id'], unique=False)
    op.create_index('idx_payments_created_by', 'payments', ['created_by'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_student_id', 'payments', ['student_id'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.Enum('follow_up', 'document_collection', 'document_verification', 'application_submission', 'visa_processing', 'payment_follow_up', 'appointment', 'call', 'email', 'other', name='task_type'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='task_priority'), server_default='medium', nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', 'cancelled', name='task_status'), server_default='pending', nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('lead_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.UUID(), nullable=True),
    sa.Column('due_date', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_tasks_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_tasks_assigned_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_tasks_assigned_to_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], name=op.f('fk_tasks_lead_id_leads'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_tasks_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index('idx_tasks_application_id', 'tasks', ['application_id'], unique=False)
    op.create_index('idx_tasks_assigned_by', 'tasks', ['assigned_by'], unique=False)
    op.create_index('idx_tasks_assigned_to', 'tasks', ['assigned_to'], unique=False)
    op.create_index('idx_tasks_due_date', 'tasks', ['due_date'], unique=False)
    op.create_index('idx_tasks_lead_id', 'tasks', ['lead_id'], unique=False)
    op.create_index('idx_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('idx_tasks_student_id', 'tasks', ['student_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.Enum('free', 'premium', name='subscription_plan'), server_default='free', nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'cancelled', name='subscription_status'), server_default='active', nullable=False),
    sa.Column('starts_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_subscriptions_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('user_id', name=op.f('uq_subscriptions_user_id'))
    )
    op.create_index('idx_subscriptions_payment_id', 'subscriptions', ['payment_id'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_subscriptions_user_id', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_payment_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_tasks_student_id', table_name='tasks')
    op.drop_index('idx_tasks_status', table_name='tasks')
    op.drop_index('idx_tasks_lead_id', table_name='tasks')
    op.drop_index('idx_tasks_due_date', table_name='tasks')
    op.drop_index('idx_tasks_assigned_to', table_name='tasks')
    op.drop_index('idx_tasks_assigned_by', table_name='tasks')
    op.drop_index('idx_tasks_application_id', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_payments_student_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_created_by', table_name='payments')
    op.drop_index('idx_payments_application_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('idx_application_status_history_changed_by', table_name='application_status_history')
    op.drop_index('idx_application_status_history_application_id', table_name='application_status_history')
    op.drop_table('application_status_history')
    op.drop_index('idx_application_documents_document_id', table_name='application_documents')
    op.drop_index('idx_application_documents_application_id', table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index('idx_applications_student_id', table_name='applications')
    op.drop_index('idx_applications_status', table_name='applications')
    op.drop_index('idx_applications_program_id', table_name='applications')
    op.drop_index('idx_applications_intake_id', table_name='applications')
    op.drop_index('idx_applications_counsellor_id', table_name='applications')
    op.drop_table('applications')
    op.drop_index('idx_intakes_program_id', table_name='intakes')
    op.drop_index('idx_intakes_is_active', table_name='intakes')
    op.drop_table('intakes')
    op.drop_index('idx_student_english_tests_test_type', table_name='student_english_tests')
    op.drop_index('idx_student_english_tests_student_profile_id', table_name='student_english_tests')
    op.drop_table('student_english_tests')
    op.drop_index('idx_programs_university_id', table_name='programs')
    op.drop_index('idx_programs_name', table_name='programs')
    op.drop_index('idx_programs_is_active', table_name='programs')
    op.drop_table('programs')
    op.drop_index('idx_lead_activities_performed_by', table_name='lead_activities')
    op.drop_index('idx_lead_activities_lead_id', table_name='lead_activities')
    op.drop_index('idx_lead_activities_created_at', table_name='lead_activities')
    op.drop_table('lead_activities')
    op.drop_index('idx_appointments_student_id', table_name='appointments')
    op.drop_index('idx_appointments_status', table_name='appointments')
    op.drop_index('idx_appointments_start_time', table_name='appointments')
    op.drop_index('idx_appointments_lead_id', table_name='appointments')
    op.drop_index('idx_appointments_counsellor_id', table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('idx_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('idx_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('idx_universities_name', table_name='universities')
    op.drop_index('idx_universities_is_active', table_name='universities')
    op.drop_index('idx_universities_country_id', table_name='universities')
    op.drop_table('universities')
    op.drop_index('idx_student_profiles_user_id', table_name='student_profiles')
    op.drop_index('idx_student_profiles_deleted_at', table_name='student_profiles', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('student_profiles')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('is_read = FALSE'))
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_leads_status', table_name='leads')
    op.drop_index('idx_leads_source', table_name='leads')
    op.drop_index('idx_leads_phone', table_name='leads')
    op.drop_index('idx_leads_next_follow_up_at', table_name='leads')
    op.drop_index('idx_leads_email_unique_not_null', table_name='leads', postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index('idx_leads_converted_user_id', table_name='leads')
    op.drop_index('idx_leads_assigned_to', table_name='leads')
    op.drop_table('leads')
    op.drop_index('idx_employee_profiles_user_id', table_name='employee_profiles')
    op.drop_index('idx_employee_profiles_manager_id', table_name='employee_profiles')
    op.drop_table('employee_profiles')
    op.drop_index('idx_documents_verified_by', table_name='documents')
    op.drop_index('idx_documents_uploaded_by', table_name='documents')
    op.drop_index('idx_documents_student_id', table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_document_type', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_activity_logs_user_id', table_name='activity_logs')
    op.drop_index('idx_activity_logs_entity_type', table_name='activity_logs')
    op.drop_index('idx_activity_logs_created_at', table_name='activity_logs')
    op.drop_index('idx_activity_logs_activity_type', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_last_login_at', table_name='users')
    op.drop_index('idx_users_deleted_at', table_name='users', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('users')
    op.drop_index('idx_countries_name', table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
