"""payroll salary structures runs and payslips

Revision ID: 9f2de836d01e
Revises: b11dbb32bef8
Create Date: 2026-08-10 22:50:36.228162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2de836d01e'
down_revision: Union[str, Sequence[str], None] = 'b11dbb32bef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('period_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'finalized', 'paid', name='payroll_run_status'), server_default='draft', nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finalized_by', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('paid_by', sa.UUID(), nullable=True),
    sa.Column('paid_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finalized_by'], ['users.id'], name=op.f('fk_payroll_runs_finalized_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_payroll_runs_generated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payroll_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paid_by'], ['users.id'], name=op.f('fk_payroll_runs_paid_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_runs')),
    sa.UniqueConstraint('organization_id', 'period_year', 'period_month', name='uq_payroll_runs_org_period')
    )
    op.create_index('idx_payroll_runs_organization_id', 'payroll_runs', ['organization_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=True),
    sa.Column('bank_account_name', sa.String(length=150), nullable=True),
    sa.Column('bank_account_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_salary_structures_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_salary_structures_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structures')),
    sa.UniqueConstraint('user_id', name=op.f('uq_salary_structures_user_id'))
    )
    op.create_index('idx_salary_structures_organization_id', 'salary_structures', ['organization_id'], unique=False)
    op.create_table('payslips',
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('basic_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='NPR', nullable=False),
    sa.Column('expected_work_days', sa.Integer(), nullable=False),
    sa.Column('present_days', sa.Integer(), nullable=False),
    sa.Column('paid_leave_days', sa.Integer(), nullable=False),
    sa.Column('unpaid_days', sa.Integer(), nullable=False),
    sa.Column('attendance_deduction', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('additions_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('deductions_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('net_pay', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payslips_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], name=op.f('fk_payslips_payroll_run_id_payroll_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payslips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips')),
    sa.UniqueConstraint('payroll_run_id', 'user_id', name='uq_payslips_run_user')
    )
    op.create_index('idx_payslips_organization_id', 'payslips', ['organization_id'], unique=False)
    op.create_index('idx_payslips_user_id', 'payslips', ['user_id'], unique=False)
    op.create_table('payslip_line_items',
    sa.Column('payslip_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('addition', 'deduction', name='payslip_line_type'), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payslip_line_items_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payslip_line_items_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payslip_id'], ['payslips.id'], name=op.f('fk_payslip_line_items_payslip_id_payslips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslip_line_items'))
    )
    op.create_index('idx_payslip_line_items_payslip_id', 'payslip_line_items', ['payslip_id'], unique=False)
    # ### end Alembic commands ###

    # Postgres 12+ allows ADD VALUE inside a transaction as long as the new value
    # isn't used within that same transaction — safe as its own migration.
    op.execute("ALTER TYPE employment_event_type ADD VALUE IF NOT EXISTS 'salary_changed'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payslip_line_items_payslip_id', table_name='payslip_line_items')
    op.drop_table('payslip_line_items')
    op.drop_index('idx_payslips_user_id', table_name='payslips')
    op.drop_index('idx_payslips_organization_id', table_name='payslips')
    op.drop_table('payslips')
    op.drop_index('idx_salary_structures_organization_id', table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index('idx_payroll_runs_organization_id', table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###

    # create_table doesn't auto-drop the enum types it implicitly creates.
    sa.Enum(name='payslip_line_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='payroll_run_status').drop(op.get_bind(), checkfirst=True)

    # Postgres has no DROP VALUE for enums — removing 'salary_changed' from
    # employment_event_type would require rebuilding the type. Not worth the
    # risk/complexity for a downgrade path that's never used in this project;
    # intentionally left in place, same precedent as 5b112471d25b (lead notification type).
