"""leave types and requests

Revision ID: b11dbb32bef8
Revises: caf650598543
Create Date: 2026-08-10 21:26:58.084246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11dbb32bef8'
down_revision: Union[str, Sequence[str], None] = 'caf650598543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_days_per_year', sa.Integer(), server_default='0', nullable=False),
    sa.Column('paid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leave_types_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_leave_types_organization_id_name')
    )
    op.create_index('idx_leave_types_organization_id', 'leave_types', ['organization_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('leave_type_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('requested_days', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('attachment_url', sa.Text(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='leave_status'), server_default='pending', nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_leave_type_id_leave_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_leave_requests_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_leave_requests_reviewed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_leave_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index('idx_leave_requests_leave_type_id', 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index('idx_leave_requests_organization_id', 'leave_requests', ['organization_id'], unique=False)
    op.create_index('idx_leave_requests_start_date', 'leave_requests', ['start_date'], unique=False)
    op.create_index('idx_leave_requests_status', 'leave_requests', ['status'], unique=False)
    op.create_index('idx_leave_requests_user_id', 'leave_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_leave_requests_user_id', table_name='leave_requests')
    op.drop_index('idx_leave_requests_status', table_name='leave_requests')
    op.drop_index('idx_leave_requests_start_date', table_name='leave_requests')
    op.drop_index('idx_leave_requests_organization_id', table_name='leave_requests')
    op.drop_index('idx_leave_requests_leave_type_id', table_name='leave_requests')
    op.drop_table('leave_requests')
    # create_table auto-creates enum types but drop_table does not auto-drop them.
    sa.Enum(name='leave_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index('idx_leave_types_organization_id', table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
