"""attendance policy and records

Revision ID: caf650598543
Revises: 30f33c7754d2
Create Date: 2026-08-10 18:03:01.361709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf650598543'
down_revision: Union[str, Sequence[str], None] = '30f33c7754d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_policies',
    sa.Column('work_days', sa.ARRAY(sa.Integer()), server_default='{0,1,2,3,4}', nullable=False),
    sa.Column('expected_start_time', sa.Time(), server_default='09:00:00', nullable=False),
    sa.Column('expected_end_time', sa.Time(), server_default='17:00:00', nullable=False),
    sa.Column('grace_period_minutes', sa.Integer(), server_default='10', nullable=False),
    sa.Column('break_minutes', sa.Integer(), server_default='60', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attendance_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_policies')),
    sa.UniqueConstraint('organization_id', name='uq_attendance_policies_organization_id')
    )
    op.create_index('idx_attendance_policies_organization_id', 'attendance_policies', ['organization_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('worked_seconds', sa.Integer(), nullable=True),
    sa.Column('overtime_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('present', 'late', 'half_day', 'on_leave', 'holiday', 'absent', 'weekend', name='attendance_status'), server_default='present', nullable=False),
    sa.Column('source', sa.Enum('web', 'manual', name='attendance_source'), server_default='web', nullable=False),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_attendance_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], name=op.f('fk_attendance_records_recorded_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_attendance_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records')),
    sa.UniqueConstraint('organization_id', 'user_id', 'date', name='uq_attendance_records_org_user_date')
    )
    op.create_index('idx_attendance_records_date', 'attendance_records', ['date'], unique=False)
    op.create_index('idx_attendance_records_organization_id', 'attendance_records', ['organization_id'], unique=False)
    op.create_index('idx_attendance_records_status', 'attendance_records', ['status'], unique=False)
    op.create_index('idx_attendance_records_user_id', 'attendance_records', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attendance_records_user_id', table_name='attendance_records')
    op.drop_index('idx_attendance_records_status', table_name='attendance_records')
    op.drop_index('idx_attendance_records_organization_id', table_name='attendance_records')
    op.drop_index('idx_attendance_records_date', table_name='attendance_records')
    op.drop_table('attendance_records')
    # create_table auto-creates enum types but drop_table does not auto-drop them.
    sa.Enum(name='attendance_source').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='attendance_status').drop(op.get_bind(), checkfirst=True)
    op.drop_index('idx_attendance_policies_organization_id', table_name='attendance_policies')
    op.drop_table('attendance_policies')
    # ### end Alembic commands ###
