"""workflow management

Revision ID: d6fbf129e273
Revises: 903d2bde03d8
Create Date: 2026-08-05 12:57:09.312902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# `document_type` already exists as a Postgres enum type from the initial migration —
# reference it with create_type=False everywhere it's reused here instead of letting
# autogenerate try to CREATE TYPE it again.
_document_type_enum = postgresql.ENUM(
    'passport', 'citizenship', 'national_id', 'academic_transcript', 'academic_certificate',
    'provisional_certificate', 'character_certificate', 'english_test', 'cv',
    'statement_of_purpose', 'recommendation_letter', 'offer_letter', 'visa',
    'financial_document', 'medical_report', 'photo', 'other',
    name='document_type', create_type=False,
)


# revision identifiers, used by Alembic.
revision: str = 'd6fbf129e273'
down_revision: Union[str, Sequence[str], None] = '903d2bde03d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_workflow_templates_country_id_countries'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_workflow_templates_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_templates')),
    sa.UniqueConstraint('slug', name=op.f('uq_workflow_templates_slug'))
    )
    op.create_index('idx_workflow_templates_country_id', 'workflow_templates', ['country_id'], unique=False)
    op.create_index('idx_workflow_templates_is_active', 'workflow_templates', ['is_active'], unique=False)
    op.create_table('workflow_stages',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], name=op.f('fk_workflow_stages_template_id_workflow_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stages')),
    sa.UniqueConstraint('template_id', 'key', name='uq_workflow_stages_template_id_key')
    )
    op.create_index('idx_workflow_stages_template_id', 'workflow_stages', ['template_id'], unique=False)
    op.create_table('workflow_stage_document_requirements',
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('document_type', _document_type_enum, nullable=True),
    sa.Column('custom_label', sa.String(length=150), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], name=op.f('fk_workflow_stage_document_requirements_stage_id_workflow_stages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_stage_document_requirements'))
    )
    op.create_index('idx_workflow_stage_document_requirements_stage_id', 'workflow_stage_document_requirements', ['stage_id'], unique=False)
    op.create_table('application_checklist_items',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('document_type', _document_type_enum, nullable=True),
    sa.Column('custom_label', sa.String(length=150), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.Enum('pending', 'submitted', 'verified', 'rejected', 'waived', name='checklist_item_status'), server_default='pending', nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_checklist_items_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_application_checklist_items_document_id_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], name=op.f('fk_application_checklist_items_stage_id_workflow_stages'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_checklist_items'))
    )
    op.create_index('idx_application_checklist_items_application_id', 'application_checklist_items', ['application_id'], unique=False)
    op.create_index('idx_application_checklist_items_stage_id', 'application_checklist_items', ['stage_id'], unique=False)
    op.create_index('idx_application_checklist_items_status', 'application_checklist_items', ['status'], unique=False)
    op.create_table('application_workflows',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'cancelled', name='application_workflow_status'), server_default='active', nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_workflows_application_id_applications'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], name=op.f('fk_application_workflows_template_id_workflow_templates'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_workflows')),
    sa.UniqueConstraint('application_id', name=op.f('uq_application_workflows_application_id'))
    )
    op.create_index('idx_application_workflows_status', 'application_workflows', ['status'], unique=False)
    op.create_index('idx_application_workflows_template_id', 'application_workflows', ['template_id'], unique=False)
    op.create_table('application_workflow_steps',
    sa.Column('application_workflow_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('stage_name_snapshot', sa.String(length=150), nullable=False),
    sa.Column('status', sa.Enum('pending', 'current', 'completed', 'failed', 'skipped', 'cancelled', name='workflow_step_status'), server_default='pending', nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_workflow_id'], ['application_workflows.id'], name=op.f('fk_application_workflow_steps_application_workflow_id_application_workflows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_application_workflow_steps_assigned_to_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], name=op.f('fk_application_workflow_steps_stage_id_workflow_stages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_application_workflow_steps_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_workflow_steps'))
    )
    op.create_index('idx_application_workflow_steps_application_workflow_id', 'application_workflow_steps', ['application_workflow_id'], unique=False)
    op.create_index('idx_application_workflow_steps_assigned_to', 'application_workflow_steps', ['assigned_to'], unique=False)
    op.create_index('idx_application_workflow_steps_stage_id', 'application_workflow_steps', ['stage_id'], unique=False)
    op.create_index('idx_application_workflow_steps_status', 'application_workflow_steps', ['status'], unique=False)
    op.create_table('workflow_step_activities',
    sa.Column('step_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.Enum('created', 'status_changed', 'note_added', 'assigned', 'document_linked', 'comment', name='workflow_activity_type'), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('old_status', sa.Enum('pending', 'current', 'completed', 'failed', 'skipped', 'cancelled', name='workflow_step_status'), nullable=True),
    sa.Column('new_status', sa.Enum('pending', 'current', 'completed', 'failed', 'skipped', 'cancelled', name='workflow_step_status'), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_workflow_step_activities_performed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['step_id'], ['application_workflow_steps.id'], name=op.f('fk_workflow_step_activities_step_id_application_workflow_steps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step_activities'))
    )
    op.create_index('idx_workflow_step_activities_created_at', 'workflow_step_activities', ['created_at'], unique=False)
    op.create_index('idx_workflow_step_activities_step_id', 'workflow_step_activities', ['step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_step_activities_step_id', table_name='workflow_step_activities')
    op.drop_index('idx_workflow_step_activities_created_at', table_name='workflow_step_activities')
    op.drop_table('workflow_step_activities')
    op.drop_index('idx_application_workflow_steps_status', table_name='application_workflow_steps')
    op.drop_index('idx_application_workflow_steps_stage_id', table_name='application_workflow_steps')
    op.drop_index('idx_application_workflow_steps_assigned_to', table_name='application_workflow_steps')
    op.drop_index('idx_application_workflow_steps_application_workflow_id', table_name='application_workflow_steps')
    op.drop_table('application_workflow_steps')
    op.drop_index('idx_application_workflows_template_id', table_name='application_workflows')
    op.drop_index('idx_application_workflows_status', table_name='application_workflows')
    op.drop_table('application_workflows')
    op.drop_index('idx_application_checklist_items_status', table_name='application_checklist_items')
    op.drop_index('idx_application_checklist_items_stage_id', table_name='application_checklist_items')
    op.drop_index('idx_application_checklist_items_application_id', table_name='application_checklist_items')
    op.drop_table('application_checklist_items')
    op.drop_index('idx_workflow_stage_document_requirements_stage_id', table_name='workflow_stage_document_requirements')
    op.drop_table('workflow_stage_document_requirements')
    op.drop_index('idx_workflow_stages_template_id', table_name='workflow_stages')
    op.drop_table('workflow_stages')
    op.drop_index('idx_workflow_templates_is_active', table_name='workflow_templates')
    op.drop_index('idx_workflow_templates_country_id', table_name='workflow_templates')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
