"""multi-tenancy phase 1: organizations and tenant scoping

Revision ID: e009a611841b
Revises: 31d14ea42645
Create Date: 2026-08-05 19:12:07.759389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e009a611841b'
down_revision: Union[str, Sequence[str], None] = '31d14ea42645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Fixed id for the organization that all pre-existing (pre-multi-tenancy) data
# is backfilled into — every row created before this migration becomes the
# first tenant, with zero data loss and zero behavior change for existing users.
DEFAULT_ORGANIZATION_ID = "00000000-0000-0000-0000-000000000001"

# organization_id is enforced NOT NULL on every tenant-owned table except:
#  - users (NULL is how a platform administrator is represented)
#  - activity_logs (a failed login for an unrecognized email has no org context)
TABLES_WITH_REQUIRED_ORG_ID = [
    "application_workflows",
    "applications",
    "appointments",
    "documents",
    "employee_profiles",
    "leads",
    "notifications",
    "payments",
    "student_profiles",
    "tasks",
    "workflow_templates",
]
ALL_TABLES_WITH_ORG_ID = TABLES_WITH_REQUIRED_ORG_ID + ["users", "activity_logs"]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('trial', 'active', 'suspended', 'cancelled', name='organization_status'), server_default='trial', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_index('idx_organizations_deleted_at', 'organizations', ['deleted_at'], unique=False, postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.create_index('idx_organizations_slug', 'organizations', ['slug'], unique=False)
    op.create_index('idx_organizations_status', 'organizations', ['status'], unique=False)
    op.add_column('activity_logs', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_activity_logs_organization_id', 'activity_logs', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_activity_logs_organization_id_organizations'), 'activity_logs', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('application_workflows', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_application_workflows_organization_id', 'application_workflows', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_application_workflows_organization_id_organizations'), 'application_workflows', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('applications', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_applications_organization_id', 'applications', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_applications_organization_id_organizations'), 'applications', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('appointments', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_appointments_organization_id', 'appointments', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_appointments_organization_id_organizations'), 'appointments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_documents_organization_id', 'documents', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_documents_organization_id_organizations'), 'documents', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('employee_profiles', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_employee_profiles_organization_id', 'employee_profiles', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_employee_profiles_organization_id_organizations'), 'employee_profiles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('leads', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_leads_organization_id', 'leads', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_leads_organization_id_organizations'), 'leads', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('notifications', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_notifications_organization_id', 'notifications', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_notifications_organization_id_organizations'), 'notifications', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('payments', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_payments_organization_id', 'payments', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_payments_organization_id_organizations'), 'payments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('student_profiles', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_student_profiles_organization_id', 'student_profiles', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_student_profiles_organization_id_organizations'), 'student_profiles', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_tasks_organization_id', 'tasks', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_tasks_organization_id_organizations'), 'tasks', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_platform_admin', sa.Boolean(), server_default='false', nullable=False))
    op.create_index('idx_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_users_organization_id_organizations'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='RESTRICT')
    op.add_column('workflow_templates', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index('idx_workflow_templates_organization_id', 'workflow_templates', ['organization_id'], unique=False)
    op.create_foreign_key(op.f('fk_workflow_templates_organization_id_organizations'), 'workflow_templates', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

    # New role value — its own statement since ADD VALUE can't run in the same
    # transaction as a subsequent use of it (same pattern as the earlier
    # 8f2a1c9d4e77 migration for finance/marketing/support/admissions/manager).
    op.execute("ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'viewer'")

    # Every row that existed before multi-tenancy becomes the first tenant.
    op.execute(
        f"""
        INSERT INTO organizations (id, name, slug, status, created_at, updated_at)
        VALUES ('{DEFAULT_ORGANIZATION_ID}', 'Default Organization', 'default', 'active', now(), now())
        """
    )
    for table in ALL_TABLES_WITH_ORG_ID:
        op.execute(
            f"UPDATE {table} SET organization_id = '{DEFAULT_ORGANIZATION_ID}' WHERE organization_id IS NULL"
        )

    # Enforce NOT NULL everywhere it belongs, now that every existing row has a value.
    for table in TABLES_WITH_REQUIRED_ORG_ID:
        op.alter_column(table, "organization_id", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # Postgres has no DROP VALUE for enums — 'viewer' stays on user_role even
    # on downgrade, same accepted no-op as every other enum addition this project.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workflow_templates_organization_id_organizations'), 'workflow_templates', type_='foreignkey')
    op.drop_index('idx_workflow_templates_organization_id', table_name='workflow_templates')
    op.drop_column('workflow_templates', 'organization_id')
    op.drop_constraint(op.f('fk_users_organization_id_organizations'), 'users', type_='foreignkey')
    op.drop_index('idx_users_organization_id', table_name='users')
    op.drop_column('users', 'is_platform_admin')
    op.drop_column('users', 'organization_id')
    op.drop_constraint(op.f('fk_tasks_organization_id_organizations'), 'tasks', type_='foreignkey')
    op.drop_index('idx_tasks_organization_id', table_name='tasks')
    op.drop_column('tasks', 'organization_id')
    op.drop_constraint(op.f('fk_student_profiles_organization_id_organizations'), 'student_profiles', type_='foreignkey')
    op.drop_index('idx_student_profiles_organization_id', table_name='student_profiles')
    op.drop_column('student_profiles', 'organization_id')
    op.drop_constraint(op.f('fk_payments_organization_id_organizations'), 'payments', type_='foreignkey')
    op.drop_index('idx_payments_organization_id', table_name='payments')
    op.drop_column('payments', 'organization_id')
    op.drop_constraint(op.f('fk_notifications_organization_id_organizations'), 'notifications', type_='foreignkey')
    op.drop_index('idx_notifications_organization_id', table_name='notifications')
    op.drop_column('notifications', 'organization_id')
    op.drop_constraint(op.f('fk_leads_organization_id_organizations'), 'leads', type_='foreignkey')
    op.drop_index('idx_leads_organization_id', table_name='leads')
    op.drop_column('leads', 'organization_id')
    op.drop_constraint(op.f('fk_employee_profiles_organization_id_organizations'), 'employee_profiles', type_='foreignkey')
    op.drop_index('idx_employee_profiles_organization_id', table_name='employee_profiles')
    op.drop_column('employee_profiles', 'organization_id')
    op.drop_constraint(op.f('fk_documents_organization_id_organizations'), 'documents', type_='foreignkey')
    op.drop_index('idx_documents_organization_id', table_name='documents')
    op.drop_column('documents', 'organization_id')
    op.drop_constraint(op.f('fk_appointments_organization_id_organizations'), 'appointments', type_='foreignkey')
    op.drop_index('idx_appointments_organization_id', table_name='appointments')
    op.drop_column('appointments', 'organization_id')
    op.drop_constraint(op.f('fk_applications_organization_id_organizations'), 'applications', type_='foreignkey')
    op.drop_index('idx_applications_organization_id', table_name='applications')
    op.drop_column('applications', 'organization_id')
    op.drop_constraint(op.f('fk_application_workflows_organization_id_organizations'), 'application_workflows', type_='foreignkey')
    op.drop_index('idx_application_workflows_organization_id', table_name='application_workflows')
    op.drop_column('application_workflows', 'organization_id')
    op.drop_constraint(op.f('fk_activity_logs_organization_id_organizations'), 'activity_logs', type_='foreignkey')
    op.drop_index('idx_activity_logs_organization_id', table_name='activity_logs')
    op.drop_column('activity_logs', 'organization_id')
    op.drop_index('idx_organizations_status', table_name='organizations')
    op.drop_index('idx_organizations_slug', table_name='organizations')
    op.drop_index('idx_organizations_deleted_at', table_name='organizations', postgresql_where=sa.text('deleted_at IS NOT NULL'))
    op.drop_table('organizations')
    # ### end Alembic commands ###
