"""phase 2b billing events and must change password

Revision ID: e74745c86748
Revises: 89cc92f54177
Create Date: 2026-08-05 20:13:32.916650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74745c86748'
down_revision: Union[str, Sequence[str], None] = '89cc92f54177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_billing_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('signup', 'seat_purchase', 'plan_change', name='billing_event_type'), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'failed', name='billing_event_status'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_organization_billing_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_billing_events'))
    )
    op.create_index('idx_organization_billing_events_created_at', 'organization_billing_events', ['created_at'], unique=False)
    op.create_index('idx_organization_billing_events_organization_id', 'organization_billing_events', ['organization_id'], unique=False)
    op.add_column('users', sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'must_change_password')
    op.drop_index('idx_organization_billing_events_organization_id', table_name='organization_billing_events')
    op.drop_index('idx_organization_billing_events_created_at', table_name='organization_billing_events')
    op.drop_table('organization_billing_events')
    # ### end Alembic commands ###
